CREATE TABLE veiculo(
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY ,
    ID_CLIENTE uuid NOT NULL,
    PLACA varchar(7) UNIQUE NOT NULL,
    FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID)
);