CREATE TABLE ordemServico(
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NUMERO INT NOT NULL GENERATED ALWAYS AS IDENTITY NOT NULL,
    STATUS varchar(50) NOT NULL,
    ID_VEICULO BIGINT NOT NULL,
    FOREIGN KEY(ID_VEICULO) REFERENCES veiculo(ID)
)