CREATE TABLE peca(
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NOME VARCHAR(120) NOT NULL,
    CODIGO VARCHAR(30) NOT NULL UNIQUE,
    PRECO NUMERIC(10,2) NOT NULL CHECK (PRECO > 0),
    QUANTIDADE_ESTOQUE INTEGER NOT NULL CHECK (QUANTIDADE_ESTOQUE >= 0)
)