CREATE TABLE item(
    ID BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    TIPO varchar(30) NOT NULL,
    VALOR_UNITARIO NUMERIC(10,2) NOT NULL CHECK ( VALOR_UNITARIO > 0),
    ID_ORDEM BIGINT NOT NULL,
    DESCRICAO varchar(500),
    HORAS numeric(4,2) check ( HORAS > 0),
    ID_PECA BIGINT,
    QUANTIDADE INT CHECK (QUANTIDADE > 0),
    FOREIGN KEY(ID_ORDEM) REFERENCES ordem_servico(ID),
    FOREIGN KEY(ID_PECA) REFERENCES peca(ID)

)